### ISSUE TITLE
Redirecting to https without https support

### ISSUE THREAD

**Issue by Kale-Ko** [fransallen/thedev.id#102]
I just got a domain kaleko.thedev.id, but when I went to use it it it redirected me to https. The problem here is the domain does not support https. Has a certificate just not been issued, or is there none? If not is there a way to disable this like with js.org?

**Comment by Codeize** [comment]
This is something you need to enable in your GitHub Pages settings, this is not down to us.

**Comment by Kale-Ko** [comment]
I am not using GitHub pages, I am using heroku

**Comment by fransallen** [comment]
Since thedev.id has a strict HSTS policy, you must enable HTTPS on your host. Can just enable TLS on Heroku I believe? Or I can enable Cloudflare proxy for you to have the subdomain HTTPS support? Let me know.

**Comment by Kale-Ko** [comment]
I have tried enabling https using heroku before, but I am using a hobby dyno which don’t support https.

**Comment by Kale-Ko** [comment]
For other projects I have had to proxy it through cloud flare to enable https

**Comment by Kale-Ko** [comment]
Upgraded and fixed it
