### ISSUE TITLE
Didnt merge!

### ISSUE THREAD

**Issue by TajuModding** [fransallen/thedev.id#105]
```
op-bot.thedev.id is improperly configured
Domain's DNS record could not be retrieved. For more information, see Learn more (InvalidDNSError). We recommend you change this to a CNAME record pointing to tajumodding.github.io.
```
Github showed error

**Comment by fransallen** [comment]
You submit **op.thedev.id**, not **op-bot.thedev.id**, see [#104](https://github.com/fransallen/thedev.id/pull/104).

**Comment by TajuModding** [comment]
okh prblm solved and do u guys support replit?

**Comment by fransallen** [comment]
As long as the service supports custom domain, this project can be used.
