### ISSUE TITLE
Custom Doman Doesn't Work Even After Merging PR

### ISSUE THREAD

**Issue by keystove** [fransallen/thedev.id#129]
![image](https://user-images.githubusercontent.com/79815764/126076031-7366ffa2-2018-4769-82b1-683f311e7684.png)

**Comment by fransallen** [comment]
Can you try again now?

**Comment by keystove** [comment]
Well it does work but I cannot enforce HTTPS.

![image](https://user-images.githubusercontent.com/79815764/126077492-81851d3d-200c-400d-872f-a85426b3240c.png)

**Comment by fransallen** [comment]
Just wait for the SSL to be issued.

**Comment by keystove** [comment]
Ok. It works now btw.
