### ISSUE TITLE
No pull request getting merged

### ISSUE THREAD

**Issue by Satindar31** [fransallen/thedev.id#229]
**Is your feature request related to a problem? Please describe.**
Yes, no pull requests getting merged

**Describe the solution you'd like**
Be more active at merging pull requests.

**Describe alternatives you've considered**
is-a.dev

**Additional context**
The last pull request was merged 8 days ago.
Thanks.

**Comment by BOssTDiscord** [comment]
now its 2 months

**Comment by thatcatdrout** [comment]
yeah this project is dead.
@fransallen pls revive this project

**Comment by its-pablo** [comment]
@fransallen if you're not willing to continue with this project, perhaps consider archiving it?

**Comment by MaskDuck** [comment]
the... last... pr.... was merged... 4+ month ago @fransallen

**Comment by legendlife** [comment]
@fransallen man archive this project if you don't wanna continue.

**Comment by mrhappyma** [comment]
common i really wanted one of these...

**Comment by RadarFolf** [comment]
Looks like this repo is officially dead lol

**Comment by fransallen** [comment]
Sorry for the delay, everyone. Currently working on it now :)
