### ISSUE TITLE
[Feature Suggestion] Better UI on the website.

### ISSUE THREAD

**Issue by harshhhdev** [fransallen/thedev.id#35]
The UI on the website has a very defaulty look to it which can possibly drive away some people.

Improve the UI, still keep it simple, but not as defaulty.

Possible alternatives -> Change the font to a monospace.

If you go ahead with this, can it be assigned to me?

**Comment by Codeize** [comment]
Hey, @harshhhdev . We have future plans to revamp the website. We'll keep everyone updated when this is happening :)
