### ISSUE TITLE
Code Not Updating!

### ISSUE THREAD

**Issue by yeetedmeme** [fransallen/thedev.id#43]
I've been updating my [website](https://ash-hnry.thedev.id), yet no changed are shown, can someone help me?

**Comment by Codeize** [comment]
Is it an organisation?

**Comment by yeetedmeme** [comment]
it is

**Comment by Codeize** [comment]
Hey. Is this issue persisiting? @yeetedmeme

**Comment by yeetedmeme** [comment]
yep @Codeize

**Comment by aalfiann** [comment]
I see it was already updated bro
